export type Product = {
  name: string
  description: string
  price: number
  images: string[]
  category: string
}

export const PRODUCT_LIST = [
  {
    name: "Espresso",
    description: "Description 1",
    price: 2300,
    images: ["prod1.jpg"],
    category: "Calientes",
  },
  {
    name: "Americano",
    description: "Description 2",
    price: 2500,
    images: ["prod2.jpg"],
    category: "Calientes",
  },
  {
    name: "Cappuccino",
    description: "Description 3",
    price: 3000,
    images: ["prod1.jpg"],
    category: "Calientes",
  },
  {
    name: "Latte",
    description: "Description 4",
    price: 3200,
    images: ["prod2.jpg"],
    category: "Calientes",
  },
  {
    name: "Mokaccino",
    description: "Description 5",
    price: 3700,
    images: ["prod1.jpg"],
    category: "Calientes",
  },
  {
    name: "Affogato",
    description: "Description 6",
    price: 3500,
    images: ["prod2.jpg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente",
    description: "Description 7",
    price: 3500,
    images: ["prod1.jpg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente para niños",
    description: "Description 8",
    price: 3200,
    images: ["prod2.jpg"],
    category: "Calientes",
  },
  {
    name: "Café Helado",
    description: "Description 9",
    price: 4200,
    images: ["prod1.jpg"],
    category: "Frías",
  },
  {
    name: "Americano Frío",
    description: "Description 10",
    price: 2600,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Latte Frío",
    description: "Description 11",
    price: 3500,
    images: ["prod1.jpg"],
    category: "Frías",
  },
  {
    name: "Moka Frío",
    description: "Description 12",
    price: 3800,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Jugo Natural",
    description: "Description 12",
    price: 3200,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Batidos",
    description: "Description 12",
    price: 3800,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Bebida",
    description: "Lata de 350 cc",
    price: 2000,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Agua Mineral",
    description: "Description 12",
    price: 2000,
    images: ["prod2.jpg"],
    category: "Frías",
  },
  {
    name: "Mate con Pava",
    description: "Description 12",
    price: 2500,
    images: ["prod2.jpg"],
    category: "Mate",
  },
  {
    name: "Mate Pomelo",
    description: "Description 12",
    price: 5000,
    images: ["prod2.jpg"],
    category: "Mate",
  },
  {
    name: "Recarga de yerba",
    description: "Description 12",
    price: 500,
    images: ["prod2.jpg"],
    category: "Mate",
  },
  {
    name: "Tetera Individual",
    description: "Description 12",
    price: 2500,
    images: ["prod2.jpg"],
    category: "Tetería",
  },
  {
    name: "Tetera Para Compartir",
    description: "Description 12",
    price: 3500,
    images: ["prod2.jpg"],
    category: "Tetería",
  },
  {
    name: "Porción de Miel",
    description: "Description 12",
    price: 500,
    images: ["prod2.jpg"],
    category: "Tetería",
  },
  {
    name: "Kuchen",
    description: "Description 12",
    price: 3000,
    images: ["prod2.jpg"],
    category: "Postres",
  },
  {
    name: "Pie de Limón",
    description: "Description 12",
    price: 3000,
    images: ["prod2.jpg"],
    category: "Postres",
  },
  {
    name: "Cheesecake",
    description: "Description 12",
    price: 3500,
    images: ["prod2.jpg"],
    category: "Postres",
  },
  {
    name: "Panqueque Manjar",
    description: "Description 12",
    price: 3000,
    images: ["prod2.jpg"],
    category: "Postres",
  },
  {
    name: "Trozo de Queque",
    description: "Description 12",
    price: 2000,
    images: ["prod2.jpg"],
    category: "Postres",
  },
  {
    name: "Calafate",
    description:
      "Queso fundido, morillas salteadas en mantequilla y verduras salteadas",
    price: 6500,
    images: ["prod2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Ciruelillo",
    description: "Pollo a la plancha, mix de hojas verdes, pesto y tomate",
    price: 6000,
    images: ["prod2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Chilco",
    description: "Queso fundido, carne mechada y cebolla caramelizada",
    price: 6500,
    images: ["prod2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Mutisia",
    description: "Queso fundido y jamón",
    price: 4000,
    images: ["prod2.jpg"],
    category: "Sandwich",
  },
]
