export type Product = {
  name: string
  shortDescription: string
  description: string[]
  price: number
  images: string[]
  category: string
}

export const PRODUCT_LIST = [
  {
    name: "Espresso",
    shortDescription: "",
    description: [],
    price: 2300,
    images: ["espresso_sq_1.jpeg", "espresso_sq_2.jpeg"],
    category: "Calientes",
  },
  {
    name: "Americano",
    shortDescription: "",
    description: [],
    price: 2500,
    images: ["americano_sq_1.jpeg"],
    category: "Calientes",
  },
  {
    name: "Cappuccino",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["capuccino_sq_1.jpeg"],
    category: "Calientes",
  },
  {
    name: "Latte",
    shortDescription: "",
    description: [],
    price: 3600,
    images: ["latte_sq_1.jpeg"],
    category: "Calientes",
  },
  {
    name: "Mokaccino",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["moka_sq_1.jpeg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["chocolate_caliente_sq_1.jpeg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente para niños",
    shortDescription: "",
    description: [],
    price: 3500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Café Helado",
    shortDescription: "Helado de vainilla, leche, café y crema.",
    description: ["Helado de vainilla, leche (puede ser sin lactosa, vegetal o entera), café y crema."],
    price: 4200,
    images: ["cafe_helado_sq_2.jpeg", "cafe_helado_sq_1.jpeg"],
    category: "Frías",
  },
  {
    name: "Affogato",
    shortDescription: "Helado de vainilla ahogado en un shot de espresso doble.",
    description: ["Helado de vainilla ahogado en un shot de espresso doble"],
    price: 3500,
    images: ["affogato_sq_1.jpeg"],
    category: "Frías",
  },
  {
    name: "Americano Frío",
    shortDescription: "",
    description: [],
    price: 3200,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Latte Frío",
    shortDescription: "",
    description: [],
    price: 3600,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Moka Frío",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["moka_frio_sq_1.jpeg"],
    category: "Frías",
  },
  {
    name: "Jugo Natural",
    shortDescription: "Frutilla, frambuesa, piña",
    description: ["Jugo natural de frutilla, frambuesa o piña"],
    price: 3200,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Batidos",
    shortDescription: "Frutilla, frambuesa o cookies",
    description: ["Batidos de leche, frutas y azúcar o galletas y crema"],
    price: 4000,
    images: ["batido_sq_1.jpeg"],
    category: "Frías",
  },
  {
    name: "Bebida",
    shortDescription: "Lata de 350 cc",
    description: [],
    price: 2000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Agua Mineral",
    shortDescription: "Con y sin gas",
    description: ["Botella de agua con o sin gas."],
    price: 2000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Mate con Pava",
    shortDescription: "",
    description: [],
    price: 2500,
    images: ["mate_con_pava_sq_1.jpeg", "mate_con_pava_sq_2.jpeg"],
    category: "Mate",
  },
  {
    name: "Mate Pomelo",
    shortDescription: "",
    description: [],
    price: 5000,
    images: ["mate_pomelo_sq_1.jpeg", "mate_pomelo_sq_2.jpeg"],
    category: "Mate",
  },
  {
    name: "Recarga de yerba",
    shortDescription: "",
    description: [],
    price: 500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Mate",
  },
  {
    name: "Tetera Individual",
    shortDescription: "Tetera de 300cc.",
    description: [
      "Tetera de 300cc.",
      "Tipos de té: Nego, negro con canela, chai, verde, jazmín.",
      "Infusiones: Menta, lavanda hierba buena, manzanilla, romero, chilco, rosa mosqueta, rodajas de limón, flor de Jamaica.",
    ],
    price: 2500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Tetería",
  },
  {
    name: "Tetera Para Compartir",
    shortDescription: "Tetera de 600 cc.",
    description: [
      "Tetera de 600cc.",
      "Tipos de té: Nego, negro con canela, chai, verde, jazmín.",
      "Infusiones: Menta, lavanda hierba buena, manzanilla, romero, chilco, rosa mosqueta, rodajas de limón, flor de Jamaica.",
    ],
    price: 3500,
    images: ["tetera_para_compartir_sq_1.jpeg"],
    category: "Tetería",
  },
  {
    name: "Porción de Miel",
    shortDescription: "",
    description: [],
    price: 500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Tetería",
  },
  {
    name: "Kuchen",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["kuchen_sq_1.jpeg"],
    category: "Postres",
  },
  {
    name: "Pie de Limón",
    shortDescription: "",
    description: [],
    price: 3300,
    images: ["pie_de_limon_sq_1.jpeg", "pie_de_limon_sq_2.jpeg"],
    category: "Postres",
  },
  {
    name: "Cheesecake",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["cheesecake_sq_1.jpeg", "cheesecake_sq_2.jpeg"],
    category: "Postres",
  },
  {
    name: "Panqueque Manjar",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Postres",
  },
  {
    name: "Trozo de Queque",
    shortDescription: "",
    description: [],
    price: 2000,
    images: ["queque_sq_1.jpeg"],
    category: "Postres",
  },
  {
    name: "Rollito de Canela",
    shortDescription: "",
    description: [],
    price: 1200,
    images: ["rollito_canela_sq_1.jpeg"],
    category: "Postres",
  },
  {
    name: "Calafate",
    shortDescription:
      "Queso fundido, morillas salteadas en mantequilla y verduras salteadas",
    description: [
      "Queso fundido, morillas salteadas en mantequilla y verduras salteadas",
    ],
    price: 7500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Ciruelillo",
    shortDescription: "Pollo a la plancha, mix de hojas verdes, pesto y tomate",
    description: ["Pollo a la plancha, mix de hojas verdes, pesto y tomate"],
    price: 7000,
    images: ["ciruelillo_sq_1.jpeg"],
    category: "Sandwich",
  },
  {
    name: "Chilco",
    shortDescription:
      "Humus de garbanzos y cilantro, mix de hojas verdes y tomate",
    description: [
      "Humus de garbanzos y cilantro, mix de hojas verdes y tomate",
    ],
    price: 7000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Mutisia",
    shortDescription: "Queso fundido y jamón",
    description: ["Queso fundido y jamón"],
    price: 4500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Paila de huevos",
    shortDescription: "Paila con 3 huevos revueltos",
    description: ["Paila con 3 huevos revueltos"],
    price: 4500,
    images: ["paila_huevos_sq_1.jpeg"],
    category: "Desayuno",
  },
]
