export type Product = {
  name: string
  shortDescription: string
  description: string[]
  price: number
  images: string[]
  category: string
}

export const PRODUCT_LIST = [
  {
    name: "Espresso",
    shortDescription: "",
    description: [],
    price: 2300,
    images: ["espresso.jpeg", "espresso2.jpeg"],
    category: "Calientes",
  },
  {
    name: "Americano",
    shortDescription: "",
    description: [],
    price: 2500,
    images: ["americano.jpeg"],
    category: "Calientes",
  },
  {
    name: "Cappuccino",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Latte",
    shortDescription: "",
    description: [],
    price: 3600,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Mokaccino",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["moka.jpeg"],
    category: "Calientes",
  },
  {
    name: "Affogato",
    shortDescription: "",
    description: [],
    price: 3500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Chocolate Caliente para niños",
    shortDescription: "",
    description: [],
    price: 3500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Calientes",
  },
  {
    name: "Café Helado",
    shortDescription: "",
    description: [],
    price: 4200,
    images: ["cafe_helado.jpeg", "cafe_helado2.jpeg"],
    category: "Frías",
  },
  {
    name: "Americano Frío",
    shortDescription: "",
    description: [],
    price: 3200,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Latte Frío",
    shortDescription: "",
    description: [],
    price: 3600,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Moka Frío",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Jugo Natural",
    shortDescription: "",
    description: [],
    price: 3200,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Batidos",
    shortDescription: "",
    description: [],
    price: 4000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Bebida",
    shortDescription: "Lata de 350 cc",
    description: [],
    price: 2000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Agua Mineral",
    shortDescription: "",
    description: [],
    price: 2000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Frías",
  },
  {
    name: "Mate con Pava",
    shortDescription: "",
    description: [],
    price: 2500,
    images: ["mate_con_pava.jpeg", "mate_con_pava2.jpeg"],
    category: "Mate",
  },
  {
    name: "Mate Pomelo",
    shortDescription: "",
    description: [],
    price: 5000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Mate",
  },
  {
    name: "Recarga de yerba",
    shortDescription: "",
    description: [],
    price: 500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Mate",
  },
  {
    name: "Tetera Individual",
    shortDescription: "Tetera de 500cc.",
    description: [
      "Tetera de 500cc.",
      "Tipos de té: Nego, negro con canela, chai, verde, jazmín.",
      "Infusiones: Menta, lavanda hierba buena, manzanilla, romero, chilco, rosa mosqueta, rodajas de limón, flor de Jamaica.",
    ],
    price: 2500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Tetería",
  },
  {
    name: "Tetera Para Compartir",
    shortDescription: "Tetera de 1 litro.",
    description: [
      "Tetera de 1 litro.",
      "Tipos de té: Nego, negro con canela, chai, verde, jazmín.",
      "Infusiones: Menta, lavanda hierba buena, manzanilla, romero, chilco, rosa mosqueta, rodajas de limón, flor de Jamaica.",
    ],
    price: 3500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Tetería",
  },
  {
    name: "Porción de Miel",
    shortDescription: "",
    description: [],
    price: 500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Tetería",
  },
  {
    name: "Kuchen",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Postres",
  },
  {
    name: "Pie de Limón",
    shortDescription: "",
    description: [],
    price: 3300,
    images: ["pie_de_limon.jpeg"],
    category: "Postres",
  },
  {
    name: "Cheesecake",
    shortDescription: "",
    description: [],
    price: 3800,
    images: ["cheesecake.jpeg"],
    category: "Postres",
  },
  {
    name: "Panqueque Manjar",
    shortDescription: "",
    description: [],
    price: 3000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Postres",
  },
  {
    name: "Trozo de Queque",
    shortDescription: "",
    description: [],
    price: 2000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Postres",
  },
  {
    name: "Calafate",
    shortDescription:
      "Queso fundido, morillas salteadas en mantequilla y verduras salteadas",
    description: [
      "Queso fundido, morillas salteadas en mantequilla y verduras salteadas",
    ],
    price: 7500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Ciruelillo",
    shortDescription: "Pollo a la plancha, mix de hojas verdes, pesto y tomate",
    description: ["Pollo a la plancha, mix de hojas verdes, pesto y tomate"],
    price: 7000,
    images: ["ciruelillo.jpeg"],
    category: "Sandwich",
  },
  {
    name: "Chilco",
    shortDescription:
      "Humus de garbanzos y cilantro, mix de hojas verdes y tomate",
    description: [
      "Humus de garbanzos y cilantro, mix de hojas verdes y tomate",
    ],
    price: 7000,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
  {
    name: "Mutisia",
    shortDescription: "Queso fundido y jamón",
    description: ["Queso fundido y jamón"],
    price: 4500,
    images: ["placeholder.jpg", "placeholder2.jpg"],
    category: "Sandwich",
  },
]
